### ISSUE TITLE
`inproc` and `ipc` transports do not release their lock files on destruction

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#251] opened 2019-05-20 15:14 UTC
This can often cause errors like:
```
Failed to acquire publish lock on CHANEL_NAME! Are you attempting multiple publishers?
```
Fortunately commit e91923d fixes the bug. This issue is just to motivate you to merge the pull request :-)

**Comment by jbendes** [comment] 2019-05-29 05:26
Duplicate of https://github.com/ZeroCM/zcm/issues/50. Closing this issue

**Closed by jbendes** 2019-05-29 05:26 UTC
